name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
          cache: false

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: todo-app-release
          path: build/app/outputs/flutter-apk/app-release.apk
        env:
          ACTIONS_ALLOW_UNSECURE_NODE_VERSION: true
          ACTIONS_RUNNER_FORCED_INTERNAL_NODE_VERSION: node20
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
